name: Build

on:
    push:
        branches: [master]
    pull_request:
    release:
        types: [created]
    schedule:
        -   cron: '0 4 * * *'

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Build and test
        strategy:
            matrix:
                php: ['8.0', '8.1']
                deps: [high]
                include:
                    -   php: 8.1
                        deps: low

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: Test & package
                if: matrix.deps == 'high'
                run: make update test

            -   name: Test & package (low)
                if: matrix.deps == 'low'
                run: make update-min test-min
